# Generated by Django 4.1.7 on 2023-03-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_section_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment_T',
            fields=[
                ('enrollmentID', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section_t')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
