# Generated by Django 4.1.7 on 2023-03-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plo_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO_T',
            fields=[
                ('coID', models.AutoField(primary_key=True, serialize=False)),
                ('coNo', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course_t')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plo_t')),
            ],
        ),
    ]
