# Generated by Django 4.1.7 on 2023-03-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_co_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_T',
            fields=[
                ('assessmentNo', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FloatField()),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.co_t')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section_t')),
            ],
        ),
    ]
