# Generated by Django 4.1.7 on 2023-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coursegrade_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade_t',
            name='studentID',
            field=models.CharField(max_length=25),
        ),
    ]
