# Generated by Django 4.1.7 on 2023-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_coursegrade_t_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_t',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_t',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
