# Generated by Django 4.1.7 on 2023-04-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_section_t_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_t',
            name='faculty',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
